name: RUN-SCRAPER
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, Windows ]
    defaults:
      run:
        working-directory: scraper-service

    steps:
      - uses: actions/checkout@v4

      - name: Copy application.properties
        run: copy "C:\actions-runner\application.properties" "src\main\resources\"
        shell: cmd
      
      - name: Run bootnow fully detached
        shell: cmd
        run: cmd /c start "" cmd /c "bootnow.bat"
