name: RUN-SCRAPER
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, Windows ]
    defaults:
      run:
        working-directory: scraper-service

    steps:
      - uses: actions/checkout@v4

      - name: Copy application.properties
        run: copy "C:\actions-runner\application.properties" "src\main\resources\"
        shell: cmd
      
      - name: Run bootnow via schtasks detached
        shell: cmd
        run: |
          schtasks /create /tn Scraper /tr "\"%CD%\bootnow.bat\"" /sc once /st 00:00 /rl limited
          schtasks /run /tn Scraper
          timeout /t 5
          schtasks /delete /tn Scraper /f
